# Generated by Django 6.0.4 on 2026-04-30 18:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dathang', '0001_initial'),
        ('nhacungcap', '0001_initial'),
        ('sanpham', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KiemKe',
            fields=[
                ('maKiemKe', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ngayKiem', models.DateTimeField()),
                ('nguoiKiem', models.CharField(max_length=100)),
                ('trangThai', models.IntegerField()),
            ],
            options={
                'db_table': 'inventory_kiemke',
                'constraints': [models.CheckConstraint(condition=models.Q(('trangThai__gte', 0)), name='kk_trangThai_gte_0_new')],
            },
        ),
        migrations.CreateModel(
            name='NhapKho',
            fields=[
                ('maPhieuNhap', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ngayNhap', models.DateTimeField()),
                ('trangthaiNhap', models.IntegerField(choices=[(0, 'Phiếu tạm'), (1, 'Đã hoàn thành'), (-1, 'Đã hủy')], default=0)),
                ('ghichu', models.TextField(blank=True, null=True)),
                ('tongtienNhap', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('donDatHang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dathang.dondathang')),
                ('nhaCungCap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhacungcap.nhacungcap')),
            ],
            options={
                'db_table': 'inventory_nhapkho',
            },
        ),
        migrations.CreateModel(
            name='PhieuNhap_CT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soluongDat', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('dongiaNhap', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('thanhTien', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('soluongThucNhan', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('phieuNhap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khohang.nhapkho')),
                ('sanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.sanpham')),
            ],
            options={
                'db_table': 'inventory_phieunhap_ct',
            },
        ),
        migrations.CreateModel(
            name='TonKho',
            fields=[
                ('sanPham', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='tonkho', serialize=False, to='sanpham.sanpham')),
                ('soluongTon', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('trangthaiCanhBao', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'inventory_tonkho',
                'constraints': [models.CheckConstraint(condition=models.Q(('soluongTon__gte', 0)), name='tk_soLuongTon_gte_0_new'), models.CheckConstraint(condition=models.Q(('trangthaiCanhBao__in', [0, 1, 2])), name='tk_trangthaiCanhBao_valid_new')],
            },
        ),
        migrations.CreateModel(
            name='TraHangNCC',
            fields=[
                ('maPhieuTra', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ngayTra', models.DateTimeField()),
                ('trangThai', models.IntegerField(choices=[(0, 'Phiếu tạm'), (1, 'Đã trả hàng'), (-1, 'Đã hủy')], default=0)),
                ('tongtienTra', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('nhaCungCap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhacungcap.nhacungcap')),
                ('phieuNhap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='khohang.nhapkho')),
            ],
            options={
                'db_table': 'inventory_trahangncc',
            },
        ),
        migrations.CreateModel(
            name='TraHangNCC_CT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soluongTra', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('dongiaTra', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('thanhTien', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('lydoTra', models.TextField()),
                ('phieuTra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khohang.trahangncc')),
                ('sanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.sanpham')),
            ],
            options={
                'db_table': 'inventory_trahangncc_ct',
            },
        ),
        migrations.CreateModel(
            name='XuatKho',
            fields=[
                ('maPhieuXuat', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ngayXuat', models.DateTimeField()),
                ('noiXuat', models.CharField(max_length=255)),
                ('trangThai', models.IntegerField(choices=[(0, 'Nháp'), (1, 'Hoàn thành'), (-1, 'Đã hủy')], default=0)),
            ],
            options={
                'db_table': 'inventory_xuatkho',
                'constraints': [models.CheckConstraint(condition=models.Q(('trangThai__gte', -1)), name='xk_trangThai_gte_minus_1_new')],
            },
        ),
        migrations.CreateModel(
            name='PhieuXuat_CT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soluongXuat', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('sanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.sanpham')),
                ('phieuXuat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khohang.xuatkho')),
            ],
            options={
                'db_table': 'inventory_phieuxuat_ct',
            },
        ),
        migrations.CreateModel(
            name='KiemKe_CT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slTonKho', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('slThucTe', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('kiemKe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='khohang.kiemke')),
                ('sanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.sanpham')),
            ],
            options={
                'db_table': 'inventory_kiemke_ct',
                'constraints': [models.UniqueConstraint(fields=('kiemKe', 'sanPham'), name='kkct_unique_kiemKe_sanPham_new'), models.CheckConstraint(condition=models.Q(('slTonKho__gte', 0)), name='kkct_slTonKho_gte_0_new'), models.CheckConstraint(condition=models.Q(('slThucTe__gte', 0)), name='kkct_slThucTe_gte_0_new')],
            },
        ),
        migrations.AddConstraint(
            model_name='nhapkho',
            constraint=models.CheckConstraint(condition=models.Q(('trangthaiNhap__gte', -1)), name='nk_trangthaiNhap_gte_minus_1_new'),
        ),
        migrations.AddConstraint(
            model_name='nhapkho',
            constraint=models.CheckConstraint(condition=models.Q(('tongtienNhap__gte', 0)), name='nk_tongtienNhap_gte_0_new'),
        ),
        migrations.AddConstraint(
            model_name='phieunhap_ct',
            constraint=models.UniqueConstraint(fields=('phieuNhap', 'sanPham'), name='pnct_unique_phieuNhap_sanPham_new'),
        ),
        migrations.AddConstraint(
            model_name='phieunhap_ct',
            constraint=models.CheckConstraint(condition=models.Q(('soluongDat__gt', 0)), name='pnct_soluongDat_gt_0_new'),
        ),
        migrations.AddConstraint(
            model_name='phieunhap_ct',
            constraint=models.CheckConstraint(condition=models.Q(('dongiaNhap__gte', 0)), name='pnct_dongiaNhap_gte_0_new'),
        ),
        migrations.AddConstraint(
            model_name='phieunhap_ct',
            constraint=models.CheckConstraint(condition=models.Q(('thanhTien__gte', 0)), name='pnct_thanhTien_gte_0_new'),
        ),
        migrations.AddConstraint(
            model_name='phieunhap_ct',
            constraint=models.CheckConstraint(condition=models.Q(('soluongThucNhan__gte', 0)), name='pnct_soluongThucNhan_gte_0_new'),
        ),
        migrations.AddConstraint(
            model_name='trahangncc',
            constraint=models.CheckConstraint(condition=models.Q(('trangThai__gte', -1)), name='thncc_trangThai_gte_minus_1_new'),
        ),
        migrations.AddConstraint(
            model_name='trahangncc',
            constraint=models.CheckConstraint(condition=models.Q(('tongtienTra__gte', 0)), name='thncc_tongtienTra_gte_0_new'),
        ),
        migrations.AddConstraint(
            model_name='trahangncc_ct',
            constraint=models.UniqueConstraint(fields=('phieuTra', 'sanPham'), name='thnccct_unique_phieuTra_sanPham_new'),
        ),
        migrations.AddConstraint(
            model_name='trahangncc_ct',
            constraint=models.CheckConstraint(condition=models.Q(('soluongTra__gt', 0)), name='thnccct_soluongTra_gt_0_new'),
        ),
        migrations.AddConstraint(
            model_name='trahangncc_ct',
            constraint=models.CheckConstraint(condition=models.Q(('dongiaTra__gte', 0)), name='thnccct_dongiaTra_gte_0_new'),
        ),
        migrations.AddConstraint(
            model_name='trahangncc_ct',
            constraint=models.CheckConstraint(condition=models.Q(('thanhTien__gte', 0)), name='thnccct_thanhTien_gte_0_new'),
        ),
        migrations.AddConstraint(
            model_name='phieuxuat_ct',
            constraint=models.UniqueConstraint(fields=('phieuXuat', 'sanPham'), name='pxct_unique_phieuXuat_sanPham_new'),
        ),
        migrations.AddConstraint(
            model_name='phieuxuat_ct',
            constraint=models.CheckConstraint(condition=models.Q(('soluongXuat__gt', 0)), name='pxct_soluongXuat_gt_0_new'),
        ),
    ]
