# Generated by Django 6.0.4 on 2026-05-01 18:34

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khohang', '0001_initial'),
        ('nhacungcap', '0002_remove_nhacungcap_ncc_unique_sodienthoai_and_more'),
        ('sanpham', '0002_remove_chitiet_sach_cts_namxuatban_gte_0_new_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoHang',
            fields=[
                ('maLo', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ngaySanXuat', models.DateField(blank=True, null=True)),
                ('hanSuDung', models.DateField(blank=True, null=True)),
                ('ngayNhapVao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Lô hàng',
                'db_table': 'inventory_lohang',
            },
        ),
        migrations.CreateModel(
            name='TonKhoChiTiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soluong', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
            options={
                'db_table': 'inventory_tonkho_chitiet',
            },
        ),
        migrations.CreateModel(
            name='ViTriKho',
            fields=[
                ('maViTri', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('khuVuc', models.CharField(max_length=100)),
                ('keKho', models.CharField(max_length=100)),
                ('oChua', models.CharField(max_length=100)),
                ('ghiChu', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Vị trí kho',
                'db_table': 'inventory_vitrikho',
            },
        ),
        migrations.RemoveConstraint(
            model_name='kiemke',
            name='kk_trangThai_gte_0_new',
        ),
        migrations.RemoveConstraint(
            model_name='kiemke_ct',
            name='kkct_unique_kiemKe_sanPham_new',
        ),
        migrations.RemoveConstraint(
            model_name='kiemke_ct',
            name='kkct_slTonKho_gte_0_new',
        ),
        migrations.RemoveConstraint(
            model_name='kiemke_ct',
            name='kkct_slThucTe_gte_0_new',
        ),
        migrations.RemoveConstraint(
            model_name='nhapkho',
            name='nk_trangthaiNhap_gte_minus_1_new',
        ),
        migrations.RemoveConstraint(
            model_name='nhapkho',
            name='nk_tongtienNhap_gte_0_new',
        ),
        migrations.RemoveConstraint(
            model_name='phieunhap_ct',
            name='pnct_unique_phieuNhap_sanPham_new',
        ),
        migrations.RemoveConstraint(
            model_name='phieunhap_ct',
            name='pnct_soluongDat_gt_0_new',
        ),
        migrations.RemoveConstraint(
            model_name='phieunhap_ct',
            name='pnct_dongiaNhap_gte_0_new',
        ),
        migrations.RemoveConstraint(
            model_name='phieunhap_ct',
            name='pnct_thanhTien_gte_0_new',
        ),
        migrations.RemoveConstraint(
            model_name='phieunhap_ct',
            name='pnct_soluongThucNhan_gte_0_new',
        ),
        migrations.RemoveConstraint(
            model_name='phieuxuat_ct',
            name='pxct_unique_phieuXuat_sanPham_new',
        ),
        migrations.RemoveConstraint(
            model_name='phieuxuat_ct',
            name='pxct_soluongXuat_gt_0_new',
        ),
        migrations.RemoveConstraint(
            model_name='tonkho',
            name='tk_soLuongTon_gte_0_new',
        ),
        migrations.RemoveConstraint(
            model_name='tonkho',
            name='tk_trangthaiCanhBao_valid_new',
        ),
        migrations.RemoveConstraint(
            model_name='trahangncc',
            name='thncc_trangThai_gte_minus_1_new',
        ),
        migrations.RemoveConstraint(
            model_name='trahangncc',
            name='thncc_tongtienTra_gte_0_new',
        ),
        migrations.RemoveConstraint(
            model_name='trahangncc_ct',
            name='thnccct_unique_phieuTra_sanPham_new',
        ),
        migrations.RemoveConstraint(
            model_name='trahangncc_ct',
            name='thnccct_soluongTra_gt_0_new',
        ),
        migrations.RemoveConstraint(
            model_name='trahangncc_ct',
            name='thnccct_dongiaTra_gte_0_new',
        ),
        migrations.RemoveConstraint(
            model_name='trahangncc_ct',
            name='thnccct_thanhTien_gte_0_new',
        ),
        migrations.RemoveConstraint(
            model_name='xuatkho',
            name='xk_trangThai_gte_minus_1_new',
        ),
        migrations.AddField(
            model_name='nhapkho',
            name='nguoiLap',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='kiemke_ct',
            name='sanPham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sanpham.sanpham'),
        ),
        migrations.AlterField(
            model_name='nhapkho',
            name='nhaCungCap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nhacungcap.nhacungcap'),
        ),
        migrations.AlterField(
            model_name='phieunhap_ct',
            name='sanPham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sanpham.sanpham'),
        ),
        migrations.AlterField(
            model_name='phieuxuat_ct',
            name='sanPham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sanpham.sanpham'),
        ),
        migrations.AlterField(
            model_name='tonkho',
            name='sanPham',
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, primary_key=True, related_name='tonkho', serialize=False, to='sanpham.sanpham'),
        ),
        migrations.AlterField(
            model_name='trahangncc',
            name='nhaCungCap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nhacungcap.nhacungcap'),
        ),
        migrations.AlterField(
            model_name='trahangncc_ct',
            name='sanPham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sanpham.sanpham'),
        ),
        migrations.AddField(
            model_name='lohang',
            name='sanPham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='lohangs', to='sanpham.sanpham'),
        ),
        migrations.AddField(
            model_name='tonkhochitiet',
            name='sanPham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sanpham.sanpham'),
        ),
        migrations.AddField(
            model_name='tonkhochitiet',
            name='viTri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='khohang.vitrikho'),
        ),
        migrations.AddField(
            model_name='kiemke_ct',
            name='viTri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='khohang.vitrikho'),
        ),
        migrations.AddField(
            model_name='phieunhap_ct',
            name='viTri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='khohang.vitrikho'),
        ),
        migrations.AddField(
            model_name='phieuxuat_ct',
            name='viTri',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='khohang.vitrikho'),
        ),
        migrations.AlterUniqueTogether(
            name='tonkhochitiet',
            unique_together={('sanPham', 'viTri')},
        ),
    ]
