# Generated by Django 6.0.4 on 2026-05-01 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('khohang', '0002_lohang_tonkhochitiet_vitrikho_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoHang',
        ),
    ]
