# Generated by Django 6.0.3 on 2026-04-02 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('maSP', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tenSP', models.CharField(max_length=255)),
                ('donViTinh', models.CharField(max_length=50)),
                ('giaBan', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tonKhoToiThieu', models.IntegerField(default=0)),
                ('trangThai', models.IntegerField(default=1)),
                ('moTa', models.TextField(blank=True, null=True)),
                ('anhSP', models.ImageField(blank=True, null=True, upload_to='products/')),
            ],
        ),
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('maDanhMuc', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tenDanhMuc', models.CharField(max_length=255)),
                ('trangThai', models.IntegerField(default=1)),
                ('maDanhMucCha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.danhmuc')),
            ],
        ),
        migrations.CreateModel(
            name='DonDatHang',
            fields=[
                ('maDatHang', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ngayDatHang', models.DateTimeField(auto_now_add=True)),
                ('trangThai', models.IntegerField()),
                ('ghiChu', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KiemKe',
            fields=[
                ('maKiemKe', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ngayKiem', models.DateTimeField()),
                ('nguoiKiem', models.CharField(max_length=100)),
                ('trangThai', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('maNCC', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tenNCC', models.CharField(max_length=255)),
                ('soDienThoai', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('diaChi', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='XuatKho',
            fields=[
                ('maPhieuXuat', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ngayXuat', models.DateTimeField()),
                ('noiXuat', models.CharField(max_length=255)),
                ('trangThai', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChiTiet_Sach',
            fields=[
                ('sanPham', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory.sanpham')),
                ('tacGia', models.CharField(max_length=255)),
                ('nhaXuatBan', models.CharField(max_length=255)),
                ('namXuatBan', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TonKho',
            fields=[
                ('sanPham', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='inventory.sanpham')),
                ('soluongTon', models.IntegerField(default=0)),
                ('trangthaiCanhBao', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='sanpham',
            name='danhMuc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.danhmuc'),
        ),
        migrations.CreateModel(
            name='DonDatHang_CT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soluongDat', models.IntegerField()),
                ('giaNhap', models.DecimalField(decimal_places=2, max_digits=15)),
                ('thanhTien', models.DecimalField(decimal_places=2, max_digits=15)),
                ('donDatHang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.dondathang')),
                ('sanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='KiemKe_CT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slTonKho', models.IntegerField()),
                ('slThucTe', models.IntegerField()),
                ('kiemKe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.kiemke')),
                ('sanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.sanpham')),
            ],
        ),
        migrations.AddField(
            model_name='sanpham',
            name='nhaCungCap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.nhacungcap'),
        ),
        migrations.AddField(
            model_name='dondathang',
            name='nhaCungCap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.nhacungcap'),
        ),
        migrations.CreateModel(
            name='NhapKho',
            fields=[
                ('maPhieuNhap', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ngayNhap', models.DateTimeField()),
                ('trangthaiNhap', models.IntegerField()),
                ('ghichu', models.TextField(blank=True, null=True)),
                ('tongtienNhap', models.DecimalField(decimal_places=2, max_digits=15)),
                ('donDatHang', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.dondathang')),
                ('nhaCungCap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.nhacungcap')),
            ],
        ),
        migrations.CreateModel(
            name='PhieuNhap_CT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soluongDat', models.IntegerField()),
                ('dongiaNhap', models.DecimalField(decimal_places=2, max_digits=15)),
                ('thanhTien', models.DecimalField(decimal_places=2, max_digits=15)),
                ('soluongThucNhan', models.IntegerField()),
                ('phieuNhap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.nhapkho')),
                ('sanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='TraHangNCC',
            fields=[
                ('maPhieuTra', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ngayTra', models.DateTimeField()),
                ('tongtienTra', models.DecimalField(decimal_places=2, max_digits=15)),
                ('nhaCungCap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.nhacungcap')),
                ('phieuNhap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.nhapkho')),
            ],
        ),
        migrations.CreateModel(
            name='TraHangNCC_CT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soluongTra', models.IntegerField()),
                ('dongiaTra', models.DecimalField(decimal_places=2, max_digits=15)),
                ('thanhTien', models.DecimalField(decimal_places=2, max_digits=15)),
                ('lydoTra', models.TextField()),
                ('phieuTra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.trahangncc')),
                ('sanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.sanpham')),
            ],
        ),
        migrations.CreateModel(
            name='PhieuXuat_CT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soluongXuat', models.IntegerField()),
                ('sanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.sanpham')),
                ('phieuXuat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.xuatkho')),
            ],
        ),
    ]
