# Generated by Django 6.0.4 on 2026-04-30 18:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nhacungcap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanhMuc',
            fields=[
                ('maDanhMuc', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tenDanhMuc', models.CharField(max_length=255)),
                ('trangThai', models.IntegerField(default=1)),
                ('maDanhMucCha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sanpham.danhmuc')),
            ],
            options={
                'db_table': 'inventory_danhmuc',
            },
        ),
        migrations.CreateModel(
            name='SanPham',
            fields=[
                ('maSP', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tenSP', models.CharField(max_length=255)),
                ('donViTinh', models.CharField(max_length=50)),
                ('giaBan', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('tonKhoToiThieu', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('trangThai', models.IntegerField(default=1)),
                ('moTa', models.TextField(blank=True, null=True)),
                ('anhSP', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('nhaCungCap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhacungcap.nhacungcap')),
                ('danhMuc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.danhmuc')),
            ],
            options={
                'db_table': 'inventory_sanpham',
            },
        ),
        migrations.CreateModel(
            name='ChiTiet_Sach',
            fields=[
                ('sanPham', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='sanpham.sanpham')),
                ('tacGia', models.CharField(max_length=255)),
                ('nhaXuatBan', models.CharField(max_length=255)),
                ('namXuatBan', models.IntegerField()),
            ],
            options={
                'db_table': 'inventory_chitiet_sach',
                'constraints': [models.CheckConstraint(condition=models.Q(('namXuatBan__gte', 0)), name='cts_namXuatBan_gte_0_new')],
            },
        ),
        migrations.AddConstraint(
            model_name='sanpham',
            constraint=models.CheckConstraint(condition=models.Q(('giaBan__gte', 0)), name='sp_giaBan_gte_0_new'),
        ),
        migrations.AddConstraint(
            model_name='sanpham',
            constraint=models.CheckConstraint(condition=models.Q(('tonKhoToiThieu__gte', 0)), name='sp_tonKhoToiThieu_gte_0_new'),
        ),
        migrations.AddConstraint(
            model_name='sanpham',
            constraint=models.CheckConstraint(condition=models.Q(('trangThai__in', [0, 1])), name='sp_trangThai_valid_new'),
        ),
        migrations.AddConstraint(
            model_name='danhmuc',
            constraint=models.CheckConstraint(condition=models.Q(('trangThai__in', [0, 1])), name='dm_trangThai_valid_new'),
        ),
        migrations.AddConstraint(
            model_name='danhmuc',
            constraint=models.CheckConstraint(condition=models.Q(('maDanhMuc', models.F('maDanhMucCha')), _negated=True), name='dm_not_self_parent_new'),
        ),
    ]
