# Generated by Django 6.0.4 on 2026-05-01 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhacungcap', '0002_remove_nhacungcap_ncc_unique_sodienthoai_and_more'),
        ('sanpham', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chitiet_sach',
            name='cts_namXuatBan_gte_0_new',
        ),
        migrations.RemoveConstraint(
            model_name='danhmuc',
            name='dm_trangThai_valid_new',
        ),
        migrations.RemoveConstraint(
            model_name='danhmuc',
            name='dm_not_self_parent_new',
        ),
        migrations.RemoveConstraint(
            model_name='sanpham',
            name='sp_giaBan_gte_0_new',
        ),
        migrations.RemoveConstraint(
            model_name='sanpham',
            name='sp_tonKhoToiThieu_gte_0_new',
        ),
        migrations.RemoveConstraint(
            model_name='sanpham',
            name='sp_trangThai_valid_new',
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='danhMuc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sanpham.danhmuc'),
        ),
        migrations.AlterField(
            model_name='sanpham',
            name='nhaCungCap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nhacungcap.nhacungcap'),
        ),
    ]
