# Generated by Django 6.0.4 on 2026-04-30 18:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nhacungcap', '0001_initial'),
        ('sanpham', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonDatHang',
            fields=[
                ('maDatHang', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ngayDatHang', models.DateTimeField(auto_now_add=True)),
                ('trangThai', models.IntegerField()),
                ('ghiChu', models.TextField(blank=True, null=True)),
                ('nhaCungCap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhacungcap.nhacungcap')),
            ],
            options={
                'db_table': 'inventory_dondathang',
            },
        ),
        migrations.CreateModel(
            name='DonDatHang_CT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soluongDat', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('giaNhap', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('thanhTien', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('donDatHang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dathang.dondathang')),
                ('sanPham', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sanpham.sanpham')),
            ],
            options={
                'db_table': 'inventory_dondathang_ct',
            },
        ),
        migrations.AddConstraint(
            model_name='dondathang',
            constraint=models.CheckConstraint(check=models.Q(('trangThai__gte', 0)), name='ddh_trangThai_gte_0_new'),
        ),
        migrations.AddConstraint(
            model_name='dondathang_ct',
            constraint=models.UniqueConstraint(fields=('donDatHang', 'sanPham'), name='ddhct_unique_donDatHang_sanPham_new'),
        ),
        migrations.AddConstraint(
            model_name='dondathang_ct',
            constraint=models.CheckConstraint(check=models.Q(('soluongDat__gt', 0)), name='ddhct_soluongDat_gt_0_new'),
        ),
        migrations.AddConstraint(
            model_name='dondathang_ct',
            constraint=models.CheckConstraint(check=models.Q(('giaNhap__gte', 0)), name='ddhct_giaNhap_gte_0_new'),
        ),
        migrations.AddConstraint(
            model_name='dondathang_ct',
            constraint=models.CheckConstraint(check=models.Q(('thanhTien__gte', 0)), name='ddhct_thanhTien_gte_0_new'),
        ),
    ]
