# Generated by Django 6.0.4 on 2026-05-01 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dathang', '0001_initial'),
        ('nhacungcap', '0002_remove_nhacungcap_ncc_unique_sodienthoai_and_more'),
        ('sanpham', '0002_remove_chitiet_sach_cts_namxuatban_gte_0_new_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dondathang',
            name='ddh_trangThai_gte_0_new',
        ),
        migrations.RemoveConstraint(
            model_name='dondathang_ct',
            name='ddhct_unique_donDatHang_sanPham_new',
        ),
        migrations.RemoveConstraint(
            model_name='dondathang_ct',
            name='ddhct_soluongDat_gt_0_new',
        ),
        migrations.RemoveConstraint(
            model_name='dondathang_ct',
            name='ddhct_giaNhap_gte_0_new',
        ),
        migrations.RemoveConstraint(
            model_name='dondathang_ct',
            name='ddhct_thanhTien_gte_0_new',
        ),
        migrations.AddField(
            model_name='dondathang',
            name='nguoiLap',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dondathang',
            name='nhaCungCap',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='nhacungcap.nhacungcap'),
        ),
        migrations.AlterField(
            model_name='dondathang_ct',
            name='donDatHang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dondathang_ct_set', to='dathang.dondathang'),
        ),
        migrations.AlterField(
            model_name='dondathang_ct',
            name='sanPham',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sanpham.sanpham'),
        ),
    ]
