# Generated by Django 6.0.4 on 2026-04-30 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('maNCC', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('tenNCC', models.CharField(max_length=255)),
                ('soDienThoai', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('diaChi', models.TextField()),
            ],
            options={
                'db_table': 'inventory_nhacungcap',
                'constraints': [models.UniqueConstraint(fields=('soDienThoai',), name='ncc_unique_soDienThoai'), models.UniqueConstraint(fields=('email',), name='ncc_unique_email')],
            },
        ),
    ]
