# Generated by Django 6.0.4 on 2026-05-01 18:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhacungcap', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='nhacungcap',
            name='ncc_unique_soDienThoai',
        ),
        migrations.RemoveConstraint(
            model_name='nhacungcap',
            name='ncc_unique_email',
        ),
        migrations.AlterField(
            model_name='nhacungcap',
            name='email',
            field=models.EmailField(error_messages={'invalid': 'Địa chỉ email không hợp lệ.', 'unique': 'Email này đã tồn tại trong hệ thống.'}, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='nhacungcap',
            name='soDienThoai',
            field=models.CharField(error_messages={'unique': 'Số điện thoại này đã tồn tại trong hệ thống.'}, max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Số điện thoại không hợp lệ.', regex='^\\+?[\\d\\s.-]{9,20}$')]),
        ),
        migrations.AddConstraint(
            model_name='nhacungcap',
            constraint=models.UniqueConstraint(fields=('soDienThoai',), name='ncc_unique_soDienThoai_v2'),
        ),
        migrations.AddConstraint(
            model_name='nhacungcap',
            constraint=models.UniqueConstraint(fields=('email',), name='ncc_unique_email_v2'),
        ),
    ]
